config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "tweets#index"

  resources :users, except: %i[index show]
  resources :tweets
  resources :comments, except: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  devise_scope :user do
    # Para evitar que al recargar la página despues de haber enviado espacios vacios
    # o valores que no pasan las validaciones no salga un error de "No route", tanto para sign_up
    # como para edit_profile
    post "users/sign_up", to: "devise/registrations#create"
    get "/users", to: "devise/registrations#edit"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  #Validates
  validates :body, presence: true, length: { maximum: 140 }

  # Associations
  belongs_to :user
  belongs_to :tweet, counter_cache: true  # counter_cache es para que acumule los comentarios, en este caso de los tweets.
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  #Validates
  validates :body, presence: true, length: { maximum: 140 }

  # Associations
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  #Devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  #Validates       
  validates :email, :username, :name, presence: true
  #Associations
  has_many :tweets, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar  # para permitir adjuntar imagenes.
  
  after_commit :add_default_avatar, on: %i[create update]
  
  private
  #Para cuando creas un usuario nuevo y no le asignas una imagen, por defecto se agregara esta imagen(user_default).
  def add_default_avatar
    unless avatar.attached?
      avatar.attach(io: File.open(
        Rails.root.join('app', 'assets', 'images', 'users', 'default.png')
      ), filename: "user_default")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!, except: %i[index show] # Para no permitir que un usuario pueda realizar cambios sin antes autenticarse

  protected
  
  # Para permitir mas parametros en un formulario
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email]) # Para logear usuario.
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email username name avatar]) # Para crear un usuario.
    devise_parameter_sanitizer.permit(:account_update, keys: %i[email username name avatar]) # Para editar un usuario.
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to comments_path # /tweets
    else
      render "new", status: :unprocessable_entity
    end
  end

  def new 
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])   
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to tweet_path(@comment.tweet_id), notice: "Comment was successfully update."
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    
    @comment.destroy
    redirect_to comment_path, status: :see_other, notice: "Comment was successfully destroyed."
  end

  def comment_params
    params.require(:comment).permit(:body, :tweet_id)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all.order(created_at: :desc)
  end

  def new
    @tweet = Tweet.new
  end
  
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id #variable generada por Devise (current_user)
    if @tweet.save
      redirect_to tweets_path # /tweets
    else
      render "new", status: :unprocessable_entity, alert: "Don't save."
    end
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = Comment.where(tweet_id: @tweet.id).order(created_at: :desc)
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "Tweet was successfully update."
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path, status: :see_other, notice: "Tweet was successfully destroyed."
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
   
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<div class="container-head header border-home">
  <h2>Edit Comment</h2>
</div>

<div class= "container-head border w-full word--break">
  <div class= "right--items">Body</div>
  <%= form_with model: @comment do |f| %>
    <div class = "flex-column">
      <div><%= f.text_area :body, :class => "boder--comment__edit"%></div>
      <div class = "button--submit"><%= f.submit "Edit", :class => "button button--comment"%></div>
    </div>
  <%end%>
</div>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetableIndividual</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-tweet">
      <header class="header">
        <nav class="navbar">
            <div><%= link_to image_tag("logo_tweet.png", :class => "login"), tweets_path, class: "fit-content"%></div>
            <div class= "flex-center-items fit-content">
              <% if user_signed_in? %>
                <li> <%= link_to image_tag("utils/edit_profile.png",:class => "items-center button--space"), edit_user_registration_path %> </li>
                <li> <%= link_to image_tag("utils/logout.png",:class => "button--reference button--space"), destroy_user_session_path, data: { turbo_method: :delete} %> </li>
                <% else %>
                <li><%= link_to image_tag("utils/login.png",:class => "button--reference button--space"), new_user_session_path %></li>
              <% end %>
            </div>
        </nav>
      </header>
    
      
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%=form_with model: tweet do |f| %>
  <%= f.text_area :body, placeholder: "Write thinking", :class => "w-full border--tweet"%>
  <div class = "button--tweet__direction"><%= f.submit "Tweet", :class => "button button--tweet" %></div>
<%end%>

app/views/tweets/_show_comment.html.erb
<%=form_with model: comment do |f| %>
   <%= f.text_area :body, placeholder: "Remember to thing before write...", :class => "w-full border--comment"%>
   <%= f.hidden_field :tweet_id, value: @tweet.id %>
   <div class = "button--comment__direction"><%= f.submit "Comment", :class => "button button--comment"%>
  <%end%>

app/views/tweets/_tweet_made.html.erb
<div class= "flex border">
  <div class = "mr-1">
    <% user = User.find(tweet.user_id)%>
    <%= image_tag(user.avatar)%>
  </div>
  <div class= "w-full word--break">
    <div class= "flex gap-1">
      <div class= "heading"><%= tweet.user.name%></div>
      <div class= "heading--regular">
        <%= "@#{tweet.user.username}"%>
        <%= time_ago_in_words(tweet.created_at)%><br>
      </div>
    </div>
    <%= tweet.body %><br/>
    <div class= "p-0 flex flex-between">
      <div>
        <%= link_to tweet_path(tweet) do %> 
        <%= image_tag("comments/orbe_comment.png") %>
        <%= tweet.comments_count%><br>
        <%end%>
      </div>
      <div>
        <% if user_signed_in? && current_user.id == tweet.user_id %>
        <%= link_to image_tag("edit.png"), edit_tweet_path(tweet), :class => "mr-1"%>
        <%= link_to image_tag("delete.png"), tweet_path(tweet), data: { turbo_method: :delete, turbo_confirm: "Sure?"} %><br>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/tweets/edit.html.erb
<div class="container-head header border-home">
 <h2>Edit Tweets</h2>
</div>
<div class= "container-head border w-full">
  <div class= "right--items">Body</div>
  <%= form_with model: @tweet do |f| %>
    <div class = "flex-column">
      <div><%= f.text_area :body, :class => "boder--comment__edit"%></div>
      <div class = "button--submit"><%= f.submit "Edit", :class => "button button--comment"%></div>
    </div>
  <%end%>
</div>

app/views/tweets/index.html.erb
  <div class="container-head header border-home">
   <h2>Home</h2>
  </div>
  <div class="">
    <% if user_signed_in?%>
    <div class = "flex border mb-2">
      <div class = "mr-1"><%= image_tag current_user.avatar%></div>
      <div class = "w-full"><%= render "form", tweet: Tweet.new %></div>
    </div>
    <%end%>
    <div>
      <% @tweets.each do |tweet| %>
      <%= render "tweet_made", tweet: tweet%>
      <%end%>
    </div>
  </div>
  

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>

app/views/tweets/show.html.erb
<h2 class = "container-head header border-home" ><%="Tweet Detail"%></h2>
<div class = "flex border mb-2">
  <div class = "mr-1">
    <% user = User.find(@tweet.user_id)%>
    <%= image_tag(user.avatar)%>
  </div>
  <div class = "word--break">
    <div class = "flex gap-1">
      <div class= "heading"><%= @tweet.user.name%></div>
      <div class = "heading--regular">
        <%= "@#{@tweet.user.username}"%>
        <%= time_ago_in_words(@tweet.created_at)%><br>
      </div>
    </div>
    <%= @tweet.body%>
    <div class = "p-0">
      <%= image_tag("comments/orbe_comment.png") %>
      <%= @tweet.comments_count %><br>
    </div>
  </div>
</div>
<div>
  <div>
    <% if user_signed_in? %>
      <div class = "flex border mb-2">
        <div class = "mr-1"><%= image_tag current_user.avatar %></div>
        <div class = "w-full "><%= render "show_comment", comment: Comment.new %></div>
      </div>
    <% end %>
  </div>
  <div>
    <% @comments.each do |comment| %>
      <div class = "border">
        <div class = "flex"> 
          <div class = "mr-1">
            <% user = User.find(comment.user_id)%>
            <%= image_tag(user.avatar)%>
          </div>
          <div class = "word--break">
            <%= "@#{comment.user.username}"%>
            <%= time_ago_in_words(comment.created_at)%><br>
            <p><%=comment.body%> </p>
          </div>
        </div>
        <div class = "button--comment__direction">
          <% if user_signed_in? && current_user.id == comment.user_id %>
            <div class = "mr-1"><%= link_to image_tag("edit.png"), edit_comment_path(comment)%></div>
            <%= link_to image_tag("delete.png"), comment_path(comment), data: { turbo_method: :delete, turbo_confirm: "Sure?"} %><br>
          <%end%>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/tweets/update.html.erb
<h1>Tweets#update</h1>
<p>Find me in app/views/tweets/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>